name: SLSA provenance
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  build:
    outputs:
      digest: ${{ steps.hash.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up golang environment
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.1.3
        with:
          go-version: 1.18
      - name: Checkout the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.3.4
        with:
          fetch-depth: 0
      - name: build
        shell: bash
        run: |
          set -euo pipefail
          go build -o actions-test .
      - name: hash
        shell: bash
        id: hash
        run: |
          set -euo pipefail
          DIGEST=$(sha256sum actions-test)
          DIGEST="${DIGEST//'%'/'%25'}"
          DIGEST="${DIGEST//$'\n'/'%0A'}"
          DIGEST="${DIGEST//$'\r'/'%0D'}"
          echo "::set-output name=digest::$DIGEST"
      - name: Upload the artifact
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v2.3.1
        with:
          name: "actions-test"
          path: "actions-test"
          if-no-files-found: error
          retention-days: 5
  provenance:
    needs: [build]
    permissions:
      id-token: write
      contents: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/provenance.yml@main
    with:
      subjects: "${{ needs.build.outputs.digest }}"
